// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.1.0.post0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/usr/local/include', '/usr/local/slepc-32/includ
//                                  e', '/usr/local/petsc-32/include', '/usr/include/m
//                                  pich', '/usr/include/hdf5/mpich', '/usr/include/ei
//                                  gen3', '/usr/local/lib/python3.6/dist-packages/ffc
//                                  /backends/ufc']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#include "ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb.h"

// Based on https://gcc.gnu.org/wiki/Visibility
#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_EXPORT __attribute__ ((dllexport))
    #else
        #define DLL_EXPORT __declspec(dllexport)
    #endif
#else
    #define DLL_EXPORT __attribute__ ((visibility ("default")))
#endif

ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise::ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise() : ufc::cell_integral()
{

}

ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise::~ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise()
{

}

const std::vector<bool> & ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise::enabled_coefficients() const
{
static const std::vector<bool> enabled({true});
return enabled;
}

void ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise::tabulate_tensor(double * A,
                                    const double * const * w,
                                    const double * coordinate_dofs,
                                    int cell_orientation) const
{
    // This function was generated using 'uflacs' representation
    // with the following integrals metadata:
    // 
    // num_cells:         None
    // optimize:          True
    // precision:         16
    // quadrature_degree: 1
    // quadrature_rule:   'default'
    // representation:    'uflacs'
    // 
    // and the following integral 0 metadata:
    // 
    // estimated_polynomial_degree: 1
    // optimize:                    True
    // precision:                   16
    // quadrature_degree:           1
    // quadrature_rule:             'default'
    // representation:              'uflacs'
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const double FE20_C0_D001_Q1[1][1][2] = { { { -1.0, 1.0 } } };
    // Unstructured piecewise computations
    double w0_d0 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w0_d0 += w[0][ic] * FE20_C0_D001_Q1[0][0][ic];
    const double J_c4 = coordinate_dofs[1] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[7] * FE20_C0_D001_Q1[0][0][1];
    const double J_c8 = coordinate_dofs[2] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[11] * FE20_C0_D001_Q1[0][0][1];
    const double J_c5 = coordinate_dofs[1] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[10] * FE20_C0_D001_Q1[0][0][1];
    const double J_c7 = coordinate_dofs[2] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[8] * FE20_C0_D001_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[3] * FE20_C0_D001_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[6] * FE20_C0_D001_Q1[0][0][1];
    const double J_c6 = coordinate_dofs[2] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[5] * FE20_C0_D001_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[4] * FE20_C0_D001_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[0] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[9] * FE20_C0_D001_Q1[0][0][1];
    const double w0_d1 = w[0][0] * FE20_C0_D001_Q1[0][0][0] + w[0][2] * FE20_C0_D001_Q1[0][0][1];
    const double w0_d2 = w[0][0] * FE20_C0_D001_Q1[0][0][0] + w[0][3] * FE20_C0_D001_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[3] * FE20_C0_D001_Q1[0][0][1];
    const double J_c4 = coordinate_dofs[1] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[7] * FE20_C0_D001_Q1[0][0][1];
    const double J_c8 = coordinate_dofs[2] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[11] * FE20_C0_D001_Q1[0][0][1];
    const double J_c5 = coordinate_dofs[1] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[10] * FE20_C0_D001_Q1[0][0][1];
    const double J_c7 = coordinate_dofs[2] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[8] * FE20_C0_D001_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[6] * FE20_C0_D001_Q1[0][0][1];
    const double J_c6 = coordinate_dofs[2] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[5] * FE20_C0_D001_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[4] * FE20_C0_D001_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[0] * FE20_C0_D001_Q1[0][0][0] + coordinate_dofs[9] * FE20_C0_D001_Q1[0][0][1];
    alignas(32) double sp[76];
    sp[0] = J_c4 * J_c8;
    sp[1] = J_c5 * J_c7;
    sp[2] = sp[0] + -1 * sp[1];
    sp[3] = J_c0 * sp[2];
    sp[4] = J_c5 * J_c6;
    sp[5] = J_c3 * J_c8;
    sp[6] = sp[4] + -1 * sp[5];
    sp[7] = J_c1 * sp[6];
    sp[8] = sp[3] + sp[7];
    sp[9] = J_c3 * J_c7;
    sp[10] = J_c4 * J_c6;
    sp[11] = sp[9] + -1 * sp[10];
    sp[12] = J_c2 * sp[11];
    sp[13] = sp[8] + sp[12];
    sp[14] = sp[2] / sp[13];
    sp[15] = w0_d0 * sp[14];
    sp[16] = J_c3 * (-1 * J_c8);
    sp[17] = sp[4] + sp[16];
    sp[18] = sp[17] / sp[13];
    sp[19] = w0_d1 * sp[18];
    sp[20] = sp[15] + sp[19];
    sp[21] = sp[11] / sp[13];
    sp[22] = w0_d2 * sp[21];
    sp[23] = sp[20] + sp[22];
    sp[24] = J_c2 * J_c7;
    sp[25] = J_c8 * (-1 * J_c1);
    sp[26] = sp[24] + sp[25];
    sp[27] = sp[26] / sp[13];
    sp[28] = w0_d0 * sp[27];
    sp[29] = J_c0 * J_c8;
    sp[30] = J_c6 * (-1 * J_c2);
    sp[31] = sp[29] + sp[30];
    sp[32] = sp[31] / sp[13];
    sp[33] = w0_d1 * sp[32];
    sp[34] = sp[28] + sp[33];
    sp[35] = J_c1 * J_c6;
    sp[36] = J_c0 * J_c7;
    sp[37] = sp[35] + -1 * sp[36];
    sp[38] = sp[37] / sp[13];
    sp[39] = w0_d2 * sp[38];
    sp[40] = sp[34] + sp[39];
    sp[41] = J_c1 * J_c5;
    sp[42] = J_c2 * J_c4;
    sp[43] = sp[41] + -1 * sp[42];
    sp[44] = sp[43] / sp[13];
    sp[45] = w0_d0 * sp[44];
    sp[46] = J_c2 * J_c3;
    sp[47] = J_c0 * J_c5;
    sp[48] = sp[46] + -1 * sp[47];
    sp[49] = sp[48] / sp[13];
    sp[50] = w0_d1 * sp[49];
    sp[51] = sp[45] + sp[50];
    sp[52] = J_c0 * J_c4;
    sp[53] = J_c1 * J_c3;
    sp[54] = sp[52] + -1 * sp[53];
    sp[55] = sp[54] / sp[13];
    sp[56] = w0_d2 * sp[55];
    sp[57] = sp[51] + sp[56];
    sp[58] = J_c4 * J_c8;
    sp[59] = J_c5 * J_c7;
    sp[60] = sp[58] + -1 * sp[59];
    sp[61] = J_c0 * sp[60];
    sp[62] = J_c5 * J_c6;
    sp[63] = J_c3 * J_c8;
    sp[64] = sp[62] + -1 * sp[63];
    sp[65] = J_c1 * sp[64];
    sp[66] = sp[61] + sp[65];
    sp[67] = J_c3 * J_c7;
    sp[68] = J_c4 * J_c6;
    sp[69] = sp[67] + -1 * sp[68];
    sp[70] = J_c2 * sp[69];
    sp[71] = sp[66] + sp[70];
    sp[72] = std::abs(sp[71]);
    sp[73] = sp[23] * sp[72];
    sp[74] = sp[40] * sp[72];
    sp[75] = sp[57] * sp[72];
    A[0] = 0.04166666666666667 * sp[73];
    A[1] = 0.04166666666666666 * sp[73];
    A[2] = 0.04166666666666666 * sp[73];
    A[3] = 0.04166666666666666 * sp[73];
    A[4] = 0.04166666666666667 * sp[74];
    A[5] = 0.04166666666666666 * sp[74];
    A[6] = 0.04166666666666666 * sp[74];
    A[7] = 0.04166666666666666 * sp[74];
    A[8] = 0.04166666666666667 * sp[75];
    A[9] = 0.04166666666666666 * sp[75];
    A[10] = 0.04166666666666666 * sp[75];
    A[11] = 0.04166666666666666 * sp[75];
}

extern "C" DLL_EXPORT ufc::cell_integral * create_ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise()
{
  return new ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise();
}


ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main() : ufc::form()
{
    // Do nothing
}

ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::~ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main()
{
    // Do nothing
}

const char * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::signature() const
{
    return "ddcc09bdc5a184a07b9e17bde074ba8a3d410ffd72c4c7b1a144ed0653cd096682f361d3743c5aab5bc4213bdbc85623723427393036d3de7d81997e1c381ea1";
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::rank() const
{
    return 1;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::num_coefficients() const
{
    return 1;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::original_coefficient_position(std::size_t i) const
{
    if (i >= 1)
    {
        throw std::runtime_error("Invalid original coefficient index.");
    }
    static const std::vector<std::size_t> position = {0};
    return position[i];
}

ufc::finite_element * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_coordinate_finite_element() const
{
    return create_ffc_element_cb3d7e966cb74d8c7ab56a87f86c179616a111bc_finite_element_main();
}

ufc::dofmap * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_coordinate_dofmap() const
{
    return create_ffc_element_cb3d7e966cb74d8c7ab56a87f86c179616a111bc_dofmap_main();
}

ufc::coordinate_mapping * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_coordinate_mapping() const
{
    return create_ffc_coordinate_mapping_5c983050994b413442e634597bb8a5b0f7e5064f_coordinate_mapping_main();
}

ufc::finite_element * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_finite_element(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_cb3d7e966cb74d8c7ab56a87f86c179616a111bc_finite_element_main();
    case 1:
        return create_ffc_element_b74a341781981c01e1612b1ea026f3d127aa2d4e_finite_element_main();
    default:
        return nullptr;
    }
}

ufc::dofmap * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_dofmap(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_cb3d7e966cb74d8c7ab56a87f86c179616a111bc_dofmap_main();
    case 1:
        return create_ffc_element_b74a341781981c01e1612b1ea026f3d127aa2d4e_dofmap_main();
    default:
        return nullptr;
    }
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_cell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_exterior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_interior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_vertex_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_custom_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_cutcell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_interface_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::max_overlap_subdomain_id() const
{
    return 0;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_cell_integrals() const
{
    return true;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_exterior_facet_integrals() const
{
    return false;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_interior_facet_integrals() const
{
    return false;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_vertex_integrals() const
{
    return false;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_custom_integrals() const
{
    return false;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_cutcell_integrals() const
{
    return false;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_interface_integrals() const
{
    return false;
}

bool ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::has_overlap_integrals() const
{
    return false;
}

ufc::cell_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_cell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::exterior_facet_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_exterior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_interior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_vertex_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_custom_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_cutcell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_interface_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_overlap_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cell_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_cell_integral() const
{
    return create_ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_cell_integral_main_otherwise();
}

ufc::exterior_facet_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_exterior_facet_integral() const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_interior_facet_integral() const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_vertex_integral() const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_custom_integral() const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_cutcell_integral() const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_interface_integral() const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main::create_default_overlap_integral() const
{
    return nullptr;
}

extern "C" DLL_EXPORT ufc::form * create_ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main()
{
  return new ffc_form_774758e774babf1e63d34273ea4bba6c78af63cb_form_main();
}

